<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.Testing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\F5M03.Api\F5M03.Api.csproj" />
  </ItemGroup>
</Project>
